# .github/workflows/release.yaml

on:
  push:
    branches:
      - 'master'

permissions:
    contents: write
    packages: write

jobs:
  
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get install -yy libpcre2-dev  libhyperscan-dev
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        goversion: "1.23"
        extra_files: LICENSE README.md
        release_name: canary
        
