# .github/workflows/release.yaml

on:
  push:
    branches:
      - "master"

permissions:
  contents: write
  packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Install dependencies
        run: |
          sudo apt-get install -yy libpcre2-dev  libhyperscan-dev
      - name: Build
        run: go build -v ./... && go build -v .
      - name: Release build artifacts
        run: zip -r logalign-linux-amd64.zip logalign LICENSE README.md
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            logalign-linux-amd64.zip
          tag_name: canary
          prerelease: true
          name: canary
          make_latest: true
